from MyMods.ReadDataFile import read_data
from day8.frequency_map import FrequencyMap

big_data = read_data("./day8/input_day8.txt")

test_data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".split("\n")


def part1():
    f_map = FrequencyMap(test_data)
    print(f_map)
    print(f_map.antennas)

def part2():
    pass
