from MyMods.ReadDataFile import read_data
from day8.frequency_map import FrequencyMap

big_data = read_data("./day8/input_day8.txt")

test_data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".split("\n")


def part1():
    f_map = FrequencyMap(big_data)
    print(f_map.antennas)
    print(f_map.antinodes)
    print(f_map.grids['A'])
    print(f_map.grids['0'])
    print(len(f_map.total_antinodes))

def part2():
    pass
